language: python
python:
 - "3.6"

install:
 - pip install python-dateutil

# command to run tests
script:
 - python3 TestApp_Sprint1.py
 - python3 TestApp_Sprint2.py
 - python3 TestApp_Sprint3.py
 - python3 TestApp_Sprint4.py
